apiVersion: yet-another-secrets.io/v1alpha1
kind: ASecret
metadata:
  name: my-app-secrets
  namespace: default
spec:
  # targetSecretName is omitted - will default to "my-app-secrets" (the ASecret name)
  awsSecretPath: /dev/myapp/secrets
  data:
    username:
      value: admin
    password:
      generatorRef:
        name: password-generator
