apiVersion: yet-another-secrets.io/v1alpha1
kind: ASecret
metadata:
  name: asecret-with-delete-policy
  namespace: yaso
spec:
  targetSecretName: my-secret
  awsSecretPath: /path/to/aws/secret
  # CleanupPolicy defines what happens when this ASecret is deleted
  # Valid values: "Skip" (default) or "Delete"
  # - "Skip": AWS secret remains untouched when ASecret is deleted
  # - "Delete": AWS secret is permanently deleted when ASecret is deleted
  cleanupPolicy: Delete
  data:
    username:
      value: admin
    password:
      generatorRef:
        name: password-generator

---
apiVersion: yet-another-secrets.io/v1alpha1
kind: ASecret
metadata:
  name: asecret-with-skip-policy
  namespace: yaso
spec:
  targetSecretName: my-secret-2
  awsSecretPath: /path/to/aws/secret-2
  # This secret will NOT be deleted from AWS when the ASecret is removed
  cleanupPolicy: Skip
  data:
    apiKey:
      value: "my-api-key"

---
apiVersion: yet-another-secrets.io/v1alpha1
kind: ASecret
metadata:
  name: asecret-default-policy
  namespace: yaso
spec:
  targetSecretName: my-secret-3
  awsSecretPath: /path/to/aws/secret-3
  # When cleanupPolicy is not specified, it defaults to "Skip"
  data:
    token:
      value: "my-token"